cluster.name: "elasticsearch-default"

node:
  name: NODE-1
  master: true
  data: true
  ingest: true

discovery.zen:
  minimum_master_nodes: 1
  ping.unicast.hosts: "127.0.0.1, [::1]"
network.host: "0.0.0.0"

http:
  compression: true
  cors:
    enabled: true
    allow-origin: "*"

searchguard:
    enterprise_modules_enabled: false
    restapi:
        roles_enabled:
          - "admin"
    ssl.transport:
        enabled: true
        enable_openssl_if_available: true
        keystore_type: JKS
        keystore_filepath: searchguard/ssl/NODE-1-keystore.jks
        keystore_password: "FkSolutions*2022"
        truststore_type: JKS
        truststore_filepath: searchguard/ssl/truststore.jks
        truststore_password: "FkSolutions*2022"
        enforce_hostname_verification: false
    ssl.http:
        enabled: false
        clientauth_mode: OPTIONAL
        enable_openssl_if_available: true
        keystore_type: JKS
        keystore_filepath: searchguard/ssl/NODE-1-keystore.jks
        keystore_password: "FkSolutions*2022"
        truststore_type: JKS
        truststore_filepath: searchguard/ssl/truststore.jks
        truststore_password: "FkSolutions*2022"
    authcz.admin_dn:
      - "CN=elastic ,OU=devops, C=COM"
